<?php

namespace Raidoxx\Entities\monsters;

use pocketmine\entity\EntitySizeInfo;
use pocketmine\entity\Location;
use pocketmine\event\entity\EntityDamageByEntityEvent;
use pocketmine\event\entity\EntityDamageEvent;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\network\mcpe\protocol\PlaySoundPacket;
use pocketmine\network\mcpe\protocol\types\entity\EntityIds;
use pocketmine\network\mcpe\protocol\types\entity\EntityMetadataFlags;
use pocketmine\player\Player;
use pocketmine\world\particle\EndermanTeleportParticle;
use Raidoxx\Entities\Atributes;
use Raidoxx\Entities\IA\types\ComplexIA;
use Raidoxx\Entities\IA\Utils\RandomPositions;
use Raidoxx\Entities\RDXBaseMob;
use Raidoxx\Entities\Temperament;
use Raidoxx\Libs\pathfinder\setting\rule\DefaultPathRules;
use Raidoxx\Libs\pathfinder\setting\Settings;

class Enderman extends RDXBaseMob
{
    public static string $networkId = EntityIds::ENDERMAN;
    public float $width = 0.6;
    public float $height = 2.9;
    public float $eyeHeight = 2.80;

    use RandomPositions;

    public function getName(): string
    {
        return "Enderman";
    }

    public function __construct(Location $location, CompoundTag $nbt = null)
    {
        parent::__construct(
            $location,
            new EntitySizeInfo($this->height, $this->width, $this->eyeHeight),
            self::$networkId,
            $this->getName(),
            new ComplexIA($this),
            new Temperament(Temperament::NEUTRAL),
            new Atributes(10, 8, 30, 2,10, 5, 40),
            Settings::get()->setPathRules(new DefaultPathRules()),
            new CompoundTag()
        );
        $this->getAtributes()->setTeleporter(true);
        $this->getEnemyManager()->addEnmies(Player::class);
    }

    public function attack(EntityDamageEvent $source): void
    {
        if($source instanceof EntityDamageByEntityEvent){
            $damager = $source->getDamager();
            $this->getAtributes()->setSpeed(14);
            $this->getNetworkProperties()->setGenericFlag(EntityMetadataFlags::ANGRY, true);
            $this->teleport($this->getRandomPositionByEntity($this));
            $this->getWorld()->addParticle($this->getPosition(), new EndermanTeleportParticle());

            if($damager instanceof Player){
                $pk = new PlaySoundPacket;
                $pk->soundName = "mob.endermen.stare";
                $pk->x = (int)$this->getPosition()->getX();
                $pk->y = (int)$this->getPosition()->getY();
                $pk->z = (int)$this->getPosition()->getZ();
                $pk->volume = 10;
                $pk->pitch = 1;
                foreach ($this->getViewers() as $player){
                    $player->getNetworkSession()->sendDataPacket($pk);
                }
            }
        }
        parent::attack($source); // TODO: Change the autogenerated stub
    }
}