<?php

namespace Raidoxx\Entities\monsters;

use pocketmine\entity\EntitySizeInfo;
use pocketmine\entity\Location;
use pocketmine\item\VanillaItems;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\network\mcpe\protocol\types\entity\EntityIds;
use pocketmine\player\Player;
use Raidoxx\Entities\Atributes;
use Raidoxx\Entities\IA\types\ComplexIA;
use Raidoxx\Entities\RDXBaseMob;
use Raidoxx\Entities\Temperament;
use Raidoxx\Libs\pathfinder\setting\rule\DefaultPathRules;
use Raidoxx\Libs\pathfinder\setting\Settings;

class Skeleton extends RDXBaseMob
{
    public static string $networkId = EntityIds::SKELETON;
    public float $width = 0.6;
    public float $height = 1.99;
    public float $eyeHeight = 1.90;

    public function getName(): string
    {
        return "Skeleton";
    }

    public function __construct(Location $location, CompoundTag $nbt = null)
    {
        parent::__construct(
            $location,
            new EntitySizeInfo($this->height, $this->width, $this->eyeHeight),
            self::$networkId,
            $this->getName(),
            new ComplexIA($this),
            new Temperament(Temperament::AGGRESSIVE),
            new Atributes(3, 5, 65, 10,30, 5, 20),
            Settings::get()->setPathRules(new DefaultPathRules()),
            new CompoundTag()
        );
        $this->getAtributes()->setShooter(true);
        $this->getEnemyManager()->addEnmies(Player::class);
    }

    public function getDrops() : array{
        return [
            VanillaItems::BONE()->setCount(mt_rand(0, 5))
        ];
    }

    public function onFirstUpdate(int $currentTick): void
    {
        $this->addItemInHand(VanillaItems::BOW());
        parent::onFirstUpdate($currentTick); // TODO: Change the autogenerated stub
    }
}